AllCops:
  Exclude:
    - '**/Vagrantfile'
    - 'vendor/**/*'
LineLength:
  Max: 120
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/SignalException:
  EnforcedStyle: only_raise
